apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-svc-http
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
  - name: proxy
    port: 10000
    targetPort: proxy
  - name: admin
    port: 9000
    targetPort: admin
