apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-svc-http
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    targetPort: http
